daytonaio/enterprise-docs

astro.config.mjs
package.json
pnpm-lock.yaml
src/content/docs/tools/vs-code-extension.md
src/content/docs/tools/vs-code.mdx
src/styles/tailwind.css
tailwind.config.js

Directory [/src/tools/vs-code]
- Structure: On the top, provide quick links to major sections being discussed. 
- Styling: 
- For the part feels like not strictly necessary, created a click to open group allow user to only click on when it is needed
- CSS styling to allow h3 headers appear on the right side, while keeping the font size less disruptive
- Added tailwind config but it was changing the whole style of astro starlight template, so leaving it out of astro.config for now
- Content: 
- Sub section introduction
- Installation: as detail as I can see and think of
- Features: Adding more details regarding each section within the extension, separating the `Creating repository` and `Managing repository` to prevent them being too long

docs: vs-code-extension

---

src/content/docs/configuration/teams.md
src/styles/_typography.scss

* changing button, line 147
* remove format and tsx
* add tables
* remove tables
* refactor tables and component css
* css spacing vscode problem"
* icons
* feat:icons
* docs: shareable preview vscode
* feat: svg icon local build
* chore:icon style adjustment
* docs: vscode-ssh
* docs: vscode grammar fix
* chore: merge main to vscode-fix branch
* chore style fix after merge main
* Revert "chore style fix after merge main"
This reverts commit cd3d32dc805ae53e556cd925dcefd1f3be85bf8d.
* Revert "Revert "chore style fix after merge main""
This reverts commit af7005fe75f2713e924da63695fe84a5b510912e.
* chore: style fix after merge
* docs: jetbrains repo confirmation in process
* docs: IDP
* docs:idps github,bitbucket,gitlab
* docs: IDP polishing
* icons:add github settings icon
* feat: add …

Docs updates 2 (#28)

---

src/content/docs/configuration/teams.md
src/content/docs/installation/idps.mdx
src/styles/_typography.scss

* Docs updates 2 (#28)
* changing button, line 147
* remove format and tsx
* add tables
* remove tables
* refactor tables and component css
* css spacing vscode problem"
* icons
* feat:icons
* docs: shareable preview vscode
* feat: svg icon local build
* chore:icon style adjustment
* docs: vscode-ssh
* docs: vscode grammar fix
* chore: merge main to vscode-fix branch
* chore style fix after merge main
* Revert "chore style fix after merge main"
This reverts commit cd3d32dc805ae53e556cd925dcefd1f3be85bf8d.
* Revert "Revert "chore style fix after merge main""
This reverts commit af7005fe75f2713e924da63695fe84a5b510912e.
* chore: style fix after merge
* docs: jetbrains repo confirmation in process
* docs: IDP
* docs:idps github,bitbucket,gitlab
* docs: IDP polishing
* icons:add github …

Add azure active directory as identity provider (#32)

---

src/content/docs/usage/ides.md

Have started adding additional IDE info - still have download info to add.

IDE Update

---

src/content/docs/usage/account.md

* docs/account: initial docset (#50)
* docs/account: initial docset
* usage/account: change admonition type
* usage/account: small heading restructure
* titles changed (#53)
---------

sync (#54)

---

src/content/docs/configuration/templates.md
src/content/docs/configuration/templates.mdx

* docs: templates update
* docs: templates
* remove unused md file
* remove style related content
* docs: templates cli
* change bullet number
* terraform update
* remove empty line in typography
* remove redundant information
* explain template index
* docs: update custom script
* docs: construct of a template
* docs: finish updating script
* docs: remove terraform and template index
* docs: add installer link

docs: templates update v2 (#45)

---

.devcontainer/devcontainer.json

Bug fix that enables building devcontainer on local machines from vs-code

devcontainer user

---

src/components/Footer.astro

This pull request fixes footer support link hyperlink.
Fixes https://github.com/daytonaio/enterprise-docs/issues/76

docs: fix footer support hyperlink

---

src/content/docs/tools/jetbrains-gateway.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/125

docs: modify jetbrains gateway plugin section

---

src/content/docs/usage/workspaces.md

Fixes https://github.com/daytonaio/enterprise-docs/issues/94

docs: add workspace classes description

---

src/content/docs/usage/workspaces.md

Fixes https://github.com/daytonaio/enterprise-docs/issues/91

docs: update workspace create flow

---

src/content/docs/usage/workspaces.md

Fixes https://github.com/daytonaio/enterprise-docs/issues/144

docs: fix typo

---

src/content/docs/administration/workspace-classes.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/149

docs: workspace class usage multiplier

---

src/content/docs/usage/ide.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/152

docs: add cursor ide

---

src/content/docs/usage/account.md

Fixes https://github.com/daytonaio/enterprise-docs/issues/124

docs: add default workspace class

---

src/content/docs/configuration/git-providers.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/128
Accidentally deleted the branch which closed the original pull request: https://github.com/daytonaio/enterprise-docs/pull/135

docs: update git providers

---

astro.config.mjs

Fixes https://github.com/daytonaio/enterprise-docs/issues/171

docs: modify sidebar sections config order

---

src/styles/components/markdown.scss

Ported style change from https://github.com/daytonaio/docs/pull/128/.

docs(style): consistent indentation formatting

---

src/content/docs/about/what-is-daytona.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/165

docs: modify about section

---

src/content/docs/administration/workspace-classes.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/180
Fixes https://github.com/daytonaio/enterprise-docs/issues/181

docs: add workspace classes display order & edit

---

src/content/docs/administration/workspace-classes.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/194

docs: update sorting by usage multiplier

---

src/content/docs/administration/quotas.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/192

docs: add quota total workspaces

---

src/content/docs/usage/account.md

Fixes https://github.com/daytonaio/enterprise-docs/issues/183

docs: add device activity

---

src/content/docs/usage/account.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/184

docs: add authentication to user settings

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/200

docs: add workspaces git branch option
